# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    # specify the version
    - image: circleci/golang:1.12
    environment:
      CODECOV_TOKEN: 40ae381c-2fc2-4fb0-859d-d0310f465995
    steps:
    - checkout
    - run: |
        go mod download
        go test -v -coverprofile=coverage.txt -covermode=count ./...
        bash <(curl -s https://codecov.io/bash)
